using System.ComponentModel.DataAnnotations;

namespace DoodleNote.Models;

/// <summary>
/// ViewModel for account registration and management.
/// Integrates with AspNetIdentity and DoodleNoteDb Database.
/// </summary>
public class AccountViewModel
{
    /// <summary>
    /// The unique identifier for the user account (Primary Key).
    /// Read-only and auto-generated by the database.
    /// </summary>
    [Display(Name = "User ID")]
    public string? UserId { get; set; }

    /// <summary>
    /// The user's email address.
    /// Required, must be unique, and must follow valid email address structure.
    /// </summary>
    [Required(ErrorMessage = "Email is required.")]
    [EmailAddress(ErrorMessage = "Email must be a valid email address.")]
    [StringLength(256, ErrorMessage = "Email cannot exceed 256 characters.")]
    public required string Email { get; set; }

    /// <summary>
    /// The user's username.
    /// Required, must be unique, minimum 5 characters, maximum 20 characters.
    /// </summary>
    [Required(ErrorMessage = "Username is required.")]
    [StringLength(20, MinimumLength = 5, ErrorMessage = "Username must be between 5 and 20 characters.")]
    [RegularExpression(@"^[a-zA-Z0-9_-]+$", ErrorMessage = "Username can only contain letters, numbers, underscores, and hyphens.")]
    public required string Username { get; set; }

    /// <summary>
    /// The user's password.
    /// Required, minimum 6 characters, maximum 100 characters.
    /// Must contain at least one number and one symbol (e.g., |, !, %).
    /// </summary>
    [Required(ErrorMessage = "Password is required.")]
    [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be between 6 and 100 characters.")]
    [DataType(DataType.Password)]
    [RegularExpression(@"^(?=.*[0-9])(?=.*[!@#$%^&*|_\-()+=\[\]{};:'""<>,.?/\\~`])[a-zA-Z0-9!@#$%^&*|_\-()+=\[\]{};:'""<>,.?/\\~`]{6,100}$",
        ErrorMessage = "Password must contain at least one number and one symbol (e.g., |, !, %).")]
    public required string Password { get; set; }

    /// <summary>
    /// Confirmation of the user's password.
    /// Used during registration to ensure the user typed the password correctly.
    /// </summary>
    [DataType(DataType.Password)]
    [Compare("Password", ErrorMessage = "Passwords do not match.")]
    [Display(Name = "Confirm Password")]
    public string? ConfirmPassword { get; set; }

    /// <summary>
    /// Indicates whether the user account has admin privileges.
    /// This property is read-only from the ViewModel perspective.
    /// Can only be set by users with IAdmin interface implementation.
    /// </summary>
    [Display(Name = "Is Admin")]
    [UIHint("HiddenInput")]
    public bool IsAdmin { get; set; } = false;
}
