using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoodleNote.Models;

/// <summary>
/// Represents a doodle note with a title, creation date, Creator, Invitees, and description.
/// </summary>
public class DoodleNote
{
	public DateTime CreatedDate { get; private set; }
	/// <summary>
	/// Unique identifier for the doodle note, automatically generated by the database.
	/// </summary>
	[Key]
	[ReadOnly(true)]
	public int NoteId { get; private set; }

	/// <summary>
	/// The title of the doodle note.
	/// </summary>
	[StringLength(25, MinimumLength = 1, ErrorMessage = "Title must be between 1 and 25 characters.")]
	public string NoteTitle { get; private set; } = string.Empty;

	/// <summary>
	/// The description of the doodle note.
	/// </summary>
	[StringLength(300, ErrorMessage = "Description cannot exceed 300 characters.")]
	public string? Description { get; private set; }

	public string? ImagePath { get; private set; }

	public string? UserId { get; private set; }
	
	public ApplicationUser? User { get; private set; }

	/// <summary>
	/// Factory method to create a new DoodleNote with normalized date handling.
	/// </summary>
	public static DoodleNote Create(string noteTitle, string? description, string? imagePath)
	{
		ArgumentNullException.ThrowIfNull(noteTitle);
		return new DoodleNote
		{
			NoteTitle = noteTitle,
			Description = description,
			CreatedDate = DateTime.Now,
			ImagePath = imagePath
		};
	}

	public void AddImagePath(string imagePath)
	{
		ImagePath = imagePath;
	}

	public void SetUser(ApplicationUser user, string userId)
	{
		User = user;
		UserId = userId;
	}
}
