using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoodleNote.Models;

/// <summary>
/// Represents a doodle note with a title, creation date, Creator, and Invitees.
/// </summary>
public class DoodleNote
{
	private DateTime _createdDate;

	/// <summary>
	/// Unique identifier for the doodle note, automatically generated by the database.
	/// </summary>
	[Key]
	[ReadOnly(true)]
	public int NoteId { get; set; }

	/// <summary>
	/// The title of the doodle note.
	/// </summary>
	[Required]
	[StringLength(25, MinimumLength = 1, ErrorMessage = "Title must be between 1 and 25 characters.")]
	public required string NoteTitle { get; set; }

	/// <summary>
	/// The date the doodle note was created.
	/// </summary>
	[DataType(DataType.Date)]
	[Column(TypeName = "date")]
	public DateTime CreatedDate
	{
		get => _createdDate;
		set => _createdDate = value.Date;
	}
}
