using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoodleNote.Models;



[PrimaryKey(nameof(UserId))]
[Index(nameof(UserName), IsUnique = true)]
public class UserAccount
{
	/// <summary>
	/// Unique identifier for the user account, automatically generated by the database.
	/// </summary>
	[Key]
	[ReadOnly(true)]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int UserId { get; private set; }

	/// <summary>
	/// The username for the user account, which must be unique and between 5 and 50 characters in length.
	/// </summary>
	[Required]
	[StringLength(50, MinimumLength = 5, ErrorMessage = "Username must be between 5 and 50 characters.")]
	public required string UserName { get; set; }

	/// <summary>
	/// Links this user account to the Identity user account.
	/// </summary>
	[Required]
	public required string AppUserId { get; set; }

	[ForeignKey(nameof(AppUserId))]
	public ApplicationUser? AppUser { get; set; }

	/// <summary>
	/// The chosen password from the user, which is stored as a hash for security reasons. This field is required and should not be empty.
	/// </summary>
	[Required]
	public required string PasswordHash { get; set; }
}
